### ISSUE TITLE
org.gwtproject.core.client.EntryPoint confusing with GWT2 com.google.gwt.core.client.EntryPoint

### ISSUE THREAD

**Issue by lofidewanto** [Vertispan/gwt-core#3]
There are two EntryPoint classes available:

- org.gwtproject.core.client.EntryPoint from gwt-core
- com.google.gwt.core.client.EntryPoint from gwt-user

If you are not careful you would use org.gwtproject.core.client.EntryPoint from gwt-core in your GWT2 webapp and all the compilations are working fine but you get errors:

`
at checkType_0_g$ (InternalPreconditions.java:133)
at castTo_0_g$ (Cast.java:75)
at Array.init_2_g$ (com_00046example_00046Example__EntryMethodHolder.java:3)
at initializeModules_0_g$ (ModuleUtils.java:44)
at apply_0_g$ (Impl.java:309)
at entry0_0_g$ (Impl.java:368)
`

It seems that the the OnModuleLoad removed entirely.

Solutions:

- Make it works for J2CL / GWT
- Remove it

@niloc132 comments: "that interface doesnt mean anything for J2CL, and doesnt work in GWT2
so we should just remove it to avoid confusion".

**Comment by niloc132** [comment]
I'm closing this issue as we've removed this interface and updating documentation to reflect this. We don't have a single way to solve this problem at this time, and need to keep thinking about it, but it doesn't belong in core any more.
